name: pusher_http_dart
description: Pusher HTTP Dart Library based on https://github.com/adaojunior/pusher
homepage: https://github.com/iWirk/pusher_dart
version: 1.0.1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  crypto: "^2.0.6"
  http: "^0.12.0+1"
dev_dependencies:
  test: '^1.5.3'
